### PR TITLE
add debugger options

### PR DESCRIPTION
**Pull request by steiler**
@hellt take a look at this.
We still need to integrate the prepareDebug() function.
The ENV Vars `DEBUG_MODE` and `NOWAIT` can be set to "true" to enable debugging and to enable to `--continue --multi-client` flags. Not sure how you want to integrate them into the script or simply rely on the active bash env vars.

### CODE REVIEW

**Comment by hellt** [comment]
thnx, will have a look

**Comment by hellt** [comment]
@steiler thanks, I cleaned up and brushed this up a bit
It works really well, so if all is good from your pov, I can merge this and write an article about it

**Comment by steiler** [comment]
Does it make sense to also make the images used (including version tag) e.g gomplate, linter etc variables you can change (e.g. update) at the top?!
There is no need to expose the cpm-filter acl id and debugger port as of today, correct?!
Beyond that, it looks good to me.

**Comment by hellt** [comment]
yes, we can make image url's+version as a script var.

I'd keep the port variable as it might be useful to change, but entry ID seems like ok to remove

**Comment by steiler** [comment]
The vars itself can stay I think. They are defaulted and if someone needs them, they can always set them.
The question is what you want to expose, hence already make settable via the `run.sh`.

**Comment by hellt** [comment]
should be fine to be kept local/unexposed

**Comment by steiler** [comment]
lgtm then

**Pull request merged**
